#!/bin/sh

for full in *.c-
do
    file=`basename $full '.c-'`

    {
       echo "===================================="
       echo "FILE: $file.c-"
       ../c- -P $file.c-
    }  > $file.test
    if cmp $file.test $file.out
    then
        echo $file.c- OK
    else
        echo $file.c- BAD
    fi
done
