#!/bin/sh
# IMPORTANT: path to c-:
cminus=../Code/c-

if [ ! -x $cminus ]
then
    echo "ERROR: the C- compiler at \"$cminus\" either does not exist or is not executable"
    echo "Be sure the cminus variable in the script gives a correct path to the compiler."
    exit 1
fi

for full in *.c-
do
    file=`basename $full '.c-'`

    {
       echo "===================================="
       echo "FILE: $file.c-"
       $cminus -M $file.c-
    }  > $file.test

    if [ -s $file.out ]
    then
        if cmp $file.test $file.out > /dev/null
        then
            echo $file.c- OK
        else
            sdiff -abd -w220 $file.test $file.out > $file.diff
            echo $file.c- BAD
        fi
    else
        echo "$file.c- BAD : No expected output for test file: $file.c-"
    fi
done
